### ISSUE TITLE
Also test before pushing to registry

### ISSUE THREAD

**Issue by erlend-aasland** [corona10/cpython_autoconf#13]
In `manifest-build-push.yml`, we should build and test before pushing. See [test-before-push](https://docs.docker.com/build/ci/github-actions/test-before-push/) docs for a nice example.

**Comment by corona10** [comment]
Looks good to me!

**Comment by corona10** [comment]
> Are you working on a PR, or would you like me to propose one?

Since you create the issue, I will give you a chance to creating a PR but if you are busy with other stuff, I can do it :)
